### PR TITLE
removed gpt generations

### LINKED ISSUE #3: Remove all ChatGPT generated code ,Comments make the codebase clean and also remove unnecessary imports
- [X] Remove ChatGPT generated code
 - Clean up comments in the codebase
 - Remove unnecessary imports
 - Provide an explanation of the changes

### PR DESCRIPTION
**Pull request by 0xBinayak**
Closes #3 

solved issue #3 

 - [X] Removed ChatGPT generated code
 - Cleaned up  comments in the codebase
 - Removed unnecessary imports

### CODE REVIEW

**Comment by 0xBinayak** [comment]
@Ironsoldier353  PTAL

**Comment by tosoham** [comment]
@Ironsoldier353 if this issue is still open, can I contribute?
ETA: 1/2 hr

**Comment by binayak9932** [comment]
[
a2394bb2-4fdd-44df-9e78-d936c7039547
](url)

**Comment by binayak9932** [comment]
a2394bb2-4fdd-44df-9e78-d936c7039547

**Pull request closed without merging**
